// <auto-generated />
using System;
using CreditoService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditoService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CreditoDbContext))]
    [Migration("20260525203641_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditoService.Domain.Entities.Credito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("aliquota");

                    b.Property<decimal>("BaseCalculo")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("base_calculo");

                    b.Property<DateOnly>("DataConstituicao")
                        .HasColumnType("date")
                        .HasColumnName("data_constituicao");

                    b.Property<string>("NumeroCredito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_credito");

                    b.Property<string>("NumeroNfse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_nfse");

                    b.Property<bool>("SimplesNacional")
                        .HasColumnType("boolean")
                        .HasColumnName("simples_nacional");

                    b.Property<string>("TipoCredito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_credito");

                    b.Property<decimal>("ValorDeducao")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor_deducao");

                    b.Property<decimal>("ValorFaturado")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor_faturado");

                    b.Property<decimal>("ValorIssqn")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor_issqn");

                    b.HasKey("Id");

                    b.HasIndex("NumeroCredito")
                        .IsUnique();

                    b.HasIndex("NumeroNfse");

                    b.ToTable("credito", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
